### ISSUE TITLE
node beginner: Google API key object must be provided

### ISSUE THREAD

**Issue by ozexpert** [Wizcorp/node-iap#16]
I get 

{ [AssertionError: Google API key object must be provided]
  name: 'AssertionError',
  actual: undefined,
  expected: true,
  operator: '==',
  message: 'Google API key object must be provided',
  generatedMessage: false }

Where do i specify Google API key object?? you said in the document that we need `keyObject` but since I'm a node first time user, not sure what that means..

also for `receipt` ... can this be the order number (=transaction id) ?

**Comment by ronkorving** [comment]
Look at https://github.com/Wizcorp/node-iap/blob/master/bin/verify-google.js for an example. Since you point out that you're a Node beginner, let me help you along by telling you that the payment object that is passed to `iap.verifyPayment` contains the same properties that are pulled from the command line. That is productId, packageName, receipt and keyObject.

This keyObject property can be one of:

- the string contents of the key JSON file.
- the Buffer contents of the key JSON file.
- the JSON parsed contents of the key JSON file.

**Comment by ozexpert** [comment]
sorry when you say key JSON file. what does that mean?
are you talking about the private key from Play Store?

**Comment by ozexpert** [comment]
Got it thanks.
