### ISSUE TITLE
Do not request access token with each verification request

### ISSUE THREAD

**Issue by Alaneor** [Wizcorp/node-iap#17]
Currently it seems that an access token for Google APIs is requested with each payment verification. This is unnecessary extra load to verify a single receipt and could cause significant delays when verifying a large amount of payments.

**Comment by ronkorving** [comment]
What would you suggest as an alternative?

**Comment by Alaneor** [comment]
My apologies, I wrote this in quite a hurry. :)

I believe it depends on what is the expected use case:

1. The verification should support multiple Google accounts
1. The verification should support only one Google account

For the latter, the solution is simple - you cache the token in the outer scope and re-use it for all requests. As an added bonus, you can have a timed function that will refresh the token after a period of time to avoid unauthenticated requests (i.e. a timer each hour or so).

If multiple accounts must be supported, I do not see an easy way for this, at least not without changing the API in a breaking manner (i.e. adding another required parameter etc.).

Let me know which way you would like to go. I should be able to put together a PR if only one account needs to be supported.

Thanks!

**Comment by ronkorving** [comment]
I think we'll want to support multiple accounts, but that is solvable by caching per packageName, right? I have no idea when the token times out, but I can also imagine renewing the token as soon as Google sends back a particular error, instead of on a timer (with a magic constant of one hour... because what happens when Google changes the expiration?).

What do you think?

PS: Thanks for offering to PR, that's really appreciated :)

**Comment by Alaneor** [comment]
I managed to get a PR together, so let's continue our discussion there -> #18 !
