### ISSUE TITLE
Determining whether Google purchase was a test transaction

### ISSUE THREAD

**Issue by DavidDurston** [Wizcorp/node-iap#28]
Hi, I have this set up and working but would also like to use it to know whether a purchase was a test transaction or not. Capable of doing this with the response.environment on iOS, but no way to do it in Android. Would it be possible to update the code that hits the server to also fetch the "orderId" from Google, or anything else that can note whether it was a sandbox/test transaction?

**Comment by KLVTZ** [comment]
The orderId should be available. I did a check on one of our receipts and I do see it:

```
Verified:
{
        "receipt": {
                "kind": "androidpublisher#subscriptionPurchase",
                "startTimeMillis": "1504969801216",
                "expiryTimeMillis": "1506186593602",
                "autoRenewing": true,
                "priceCurrencyCode": "USD",
                "priceAmountMicros": "delta",
                "countryCode": "US",
                "developerPayload": "omega",
                "paymentState": 2,
                "orderId": "GPA.****************"
        },
        "transactionId": "beta",
        "productId": "zeta",
        "platform": "google"
}
```

Here are the available fields:

https://developers.google.com/android-publisher/api-ref/purchases/subscriptions

I believe we upstream these and don't remove any data returned from Google.

I'm not really sure the best way to identify a production purchase. For us, we use a similar productId across our testing and production instances. This is to support compatibility between our system and the different environments google offers. Perhaps you can have a different product in testing? But that might not accomplish your end-goal? Another thought is to standardize the email you use when testing. That way, you can easily identify a test purchase because the `developerPayload` property should contain the email.

Just some thoughts.

**Comment by DavidDurston** [comment]
Hi, thanks for getting back to this. Unfortunately, I learned that Google updated their API response back in April/May and that "orderId" is now included in Sandbox purchases. Previously, it was not, and that was how one would distinguish Test vs Real transactions. There's no longer a way to do this, unfortunately.

**Comment by KLVTZ** [comment]
@DavidDurston I would suggest the following:

> Standardize the email you use when testing. That way, you can easily identify a test purchase because the developerPayload property should contain the email.

You can choose a test domain (i.e. @companytest.com) and then use that to identify test purchases from production.

**Comment by ronkorving** [comment]
I guess that concludes this issue? I'll close it, but feel free to reopen if you have further questions.
