### ISSUE TITLE
Not working for Google

### ISSUE THREAD

**Issue by mkgareja** [Wizcorp/node-iap#31]
For apple order it's it's working fine but for google order, the response is undefined also it's not giving any error. i m using below configuration.Can you please help me out.

var platform = 'google';
var payment = {
    receipt: '*******************', // always required
    productId: 'monthly_subscription',
    packageName: 'com.**********.io',
    keyObject:'../*********.json'
};

Thanks

**Comment by KLVTZ** [comment]
Hello @mkgareja 

Let's see if your receipt and credentials works with the available binary inside the `bin` folder:

```
./verify-google.js --productId=name-of-product --packageName=name-of-package --receipt='test-receipt-hash' --keyFile=google.json --subscription=true;
```

The key file should be valid JSON with the following format:

```
{
        "private_key": "",
        "client_email": ""
}
```

Make sure you include the entire private key.  

I'm not sure if your receipt is a subscription or not so that last flag may be optional.

**Comment by mkgareja** [comment]
Thanks, @KLVTZ 
it's work.
